/* PortMap header for avr-halib
 * generated by avr-pmgen 0.05 from test.portmap
 * 
 * Do not modify this file unless you really know what you are doing! * Changetest.portmap ...
 * 
 */

#include <stdint.h>


class Button0
{
public:
	enum { pressedLevel = false, usePullup = true };
	bool : 4;
	bool pinButton: 1;		// PINA, bit 4
	bool : 7;
	bool ddrButton: 1;		// DDRA, bit 4
	bool : 7;
	bool portButton: 1;		// PORTA, bit 4
};

class Button1
{
public:
	enum { pressedLevel = false, usePullup = true };
	bool : 5;
	bool pinButton: 1;		// PINA, bit 5
	bool : 7;
	bool ddrButton: 1;		// DDRA, bit 5
	bool : 7;
	bool portButton: 1;		// PORTA, bit 5
};

class Button2
{
public:
	enum { pressedLevel = false, usePullup = true };
	bool : 6;
	bool pinButton: 1;		// PINA, bit 6
	bool : 7;
	bool ddrButton: 1;		// DDRA, bit 6
	bool : 7;
	bool portButton: 1;		// PORTA, bit 6
};

class Button3
{
public:
	enum { pressedLevel = false, usePullup = true };
	bool : 7;
	bool pinButton: 1;		// PINA, bit 7
	bool : 7;
	bool ddrButton: 1;		// DDRA, bit 7
	bool : 7;
	bool portButton: 1;		// PORTA, bit 7
};

class Led0
{
public:
	enum { onLevel = true };
	bool pinLed: 1;		// PINA, bit 0
	bool : 7;
	bool ddrLed: 1;		// DDRA, bit 0
	bool : 7;
	bool portLed: 1;		// PORTA, bit 0
};

class Led1
{
public:
	enum { onLevel = true };
	bool : 1;
	bool pinLed: 1;		// PINA, bit 1
	bool : 7;
	bool ddrLed: 1;		// DDRA, bit 1
	bool : 7;
	bool portLed: 1;		// PORTA, bit 1
};

class Led2
{
public:
	enum { onLevel = true };
	bool : 2;
	bool pinLed: 1;		// PINA, bit 2
	bool : 7;
	bool ddrLed: 1;		// DDRA, bit 2
	bool : 7;
	bool portLed: 1;		// PORTA, bit 2
};

class Led3
{
public:
	enum { onLevel = true };
	bool : 3;
	bool pinLed: 1;		// PINA, bit 3
	bool : 7;
	bool ddrLed: 1;		// DDRA, bit 3
	bool : 7;
	bool portLed: 1;		// PORTA, bit 3
};

class LedBlock0123
{
public:
	enum { onLevel = 0xff };
	uint8_t pinLed0123: 4;		// PINA, bit 0-3
	uint8_t : 4;
	uint8_t ddrLed0123: 4;		// DDRA, bit 0-3
	uint8_t : 4;
	uint8_t portLed0123: 4;	// PORTA, bit 0-3

	void setLedsPin(uint8_t i)
	{
		pinLed0123 = i;
	}
	uint8_t getLedsPin()
	{
		return pinLed0123;
	}
	void setLedsDdr(uint8_t i)
	{
		ddrLed0123 = i;
	}
	uint8_t getLedsDdr()
	{
		return ddrLed0123;
	}
	void setLedsPort(uint8_t i)
	{
		portLed0123 = i;
	}
	uint8_t getLedsPort()
	{
		return portLed0123;
	}

};

class ButtonBlock0123
{
public:
	enum { pressedLevel = 0xff, usePullup = 0xff };
	uint8_t : 4;
	uint8_t pinButton0123: 4;	// PINA, bit 4-7
	uint8_t : 4;
	uint8_t ddrButton0123: 4;		// DDRA, bit 4-7
	uint8_t : 4;
	uint8_t portButton0123: 4;	// PORTA, bit 4-7

	void setButtonsPin(uint8_t i)
	{
		pinButton0123 = i;
	}
	uint8_t getButtonsPin()
	{
		return pinButton0123;
	}
	void setButtonsDdr(uint8_t i)
	{
		ddrButton0123 = i;
	}
	uint8_t getButtonsDdr()
	{
		return ddrButton0123;
	}
	void setButtonsPort(uint8_t i)
	{
		portButton0123 = i;
	}
	uint8_t getButtonsPort()
	{
		return portButton0123;
	}

};


