/* PortMap header for avr-halib
 * generated by avr-pmgen 0.05 from test.portmap
 * 
 * Do not modify this file unless you really know what you are doing! * Changetest.portmap ...
 * 
 */

#include <stdint.h>


struct Button0
{
	volatile bool : 4;
	volatile bool pinButton: 1;		// PINA, bit 4
	volatile bool : 7;
	volatile bool ddrButton: 1;		// DDRA, bit 4
	volatile bool : 7;
	volatile bool portButton: 1;		// PORTA, bit 4
	enum { pressedLevel = true, usePullup = true };
};

struct Button1
{
	volatile bool : 5;
	volatile bool pinButton: 1;		// PINA, bit 5
	volatile bool : 7;
	volatile bool ddrButton: 1;		// DDRA, bit 5
	volatile bool : 7;
	volatile bool portButton: 1;		// PORTA, bit 5
};

struct Button2
{
	volatile bool : 6;
	volatile bool pinButton: 1;		// PINA, bit 6
	volatile bool : 7;
	volatile bool ddrButton: 1;		// DDRA, bit 6
	volatile bool : 7;
	volatile bool portButton: 1;		// PORTA, bit 6
};

struct Button3
{
	volatile bool : 7;
	volatile bool pinButton: 1;		// PINA, bit 7
	volatile bool : 7;
	volatile bool ddrButton: 1;		// DDRA, bit 7
	volatile bool : 7;
	volatile bool portButton: 1;		// PORTA, bit 7
};

struct Led0
{
	enum { onLevel = true };
	volatile bool pinLed: 1;		// PINA, bit 0
	volatile bool : 7;
	volatile bool ddrLed: 1;		// DDRA, bit 0
	volatile bool : 7;
	volatile bool portLed: 1;		// PORTA, bit 0
};

struct Led1
{
	volatile bool : 1;
	volatile bool pinLed: 1;		// PINA, bit 1
	volatile bool : 7;
	volatile bool ddrLed: 1;		// DDRA, bit 1
	volatile bool : 7;
	volatile bool portLed: 1;		// PORTA, bit 1
};

struct Led2
{
	volatile bool : 2;
	volatile bool pinLed: 1;		// PINA, bit 2
	volatile bool : 7;
	volatile bool ddrLed: 1;		// DDRA, bit 2
	volatile bool : 7;
	volatile bool portLed: 1;		// PORTA, bit 2
};

struct Led3
{
	volatile bool : 3;
	volatile bool pinLed: 1;		// PINA, bit 3
	volatile bool : 7;
	volatile bool ddrLed: 1;		// DDRA, bit 3
	volatile bool : 7;
	volatile bool portLed: 1;		// PORTA, bit 3
};



